"""CNMV Entity Catalog — Definitions, descriptions, and M&A relevance.

Provides pedagogical layer so any user understands what each entity type means
without financial knowledge.
"""

CNMV_ENTITY_CATALOG = {
    "scr": {
        "code": "SCR",
        "name": "Sociedad de Capital Riesgo",
        "short_description": "Vehiculo que invierte directamente en empresas no cotizadas.",
        "long_description": "Sociedad regulada por la CNMV cuya actividad principal consiste en adquirir participaciones en companias privadas con potencial de crecimiento.",
        "buyer_relevance": "Posible comprador financiero de empresas.",
        "mna_relevance": 5,
        "mna_label": "Muy relevante para compra de empresas",
        "example_use_case": "Identificar potenciales compradores financieros para un proceso de venta.",
        "category": "vehicle",
    },
    "fcr": {
        "code": "FCR",
        "name": "Fondo de Capital Riesgo",
        "short_description": "Fondo especializado en invertir en companias privadas.",
        "long_description": "Vehiculo de inversion gestionado por una gestora profesional que capta capital de inversores para invertir en empresas.",
        "buyer_relevance": "Comprador financiero potencial.",
        "mna_relevance": 5,
        "mna_label": "Muy relevante para compra de empresas",
        "example_use_case": "Comprador financiero potencial en procesos de M&A.",
        "category": "vehicle",
    },
    "fcr_europeo": {
        "code": "FCR EU",
        "name": "Fondo de Capital Riesgo Europeo",
        "short_description": "Fondo de inversion con pasaporte europeo.",
        "long_description": "Vehiculo regulado bajo normativa europea que puede invertir en empresas de distintos paises de la Union Europea.",
        "buyer_relevance": "Comprador internacional potencial.",
        "mna_relevance": 5,
        "mna_label": "Muy relevante para compra de empresas",
        "example_use_case": "Comprador cross-border con capacidad de invertir en toda la UE.",
        "category": "vehicle",
    },
    "sgeic": {
        "code": "SGEIC",
        "name": "Sociedad Gestora de Entidades de Inversion Colectiva de Tipo Cerrado",
        "short_description": "Gestora profesional de fondos de capital riesgo.",
        "long_description": "Entidad responsable de gestionar fondos y sociedades de capital riesgo, tomando decisiones de inversion y desinversion.",
        "buyer_relevance": "Identificacion de compradores financieros.",
        "mna_relevance": 5,
        "mna_label": "Critica para identificar compradores",
        "example_use_case": "Contactar gestoras que buscan activamente empresas para invertir.",
        "category": "manager",
    },
    "sgiic": {
        "code": "SGIIC",
        "name": "Sociedad Gestora de Instituciones de Inversion Colectiva",
        "short_description": "Gestora de fondos de inversion tradicionales.",
        "long_description": "Entidad especializada en la gestion de fondos de inversion, SICAV y otros vehiculos de inversion colectiva.",
        "buyer_relevance": "Identificacion de actores financieros relevantes.",
        "mna_relevance": 3,
        "mna_label": "Interes medio",
        "example_use_case": "Identificar gestoras con fondos que podrian invertir en determinados sectores.",
        "category": "manager",
    },
    "eaf": {
        "code": "EAF",
        "name": "Empresa de Asesoramiento Financiero",
        "short_description": "Firma especializada en asesoramiento de inversiones.",
        "long_description": "Entidad regulada que presta asesoramiento financiero a inversores, empresas y patrimonios.",
        "buyer_relevance": "Generacion de deal flow y contactos.",
        "mna_relevance": 3,
        "mna_label": "Interes medio",
        "example_use_case": "Fuente de contactos y deal flow en procesos de compraventa.",
        "category": "manager",
    },
    "eafn": {
        "code": "EAF",
        "name": "Empresa de Asesoramiento Financiero (Nacimiento)",
        "short_description": "EAF de reciente creacion.",
        "long_description": "Entidad de asesoramiento financiero en fase inicial de actividad.",
        "buyer_relevance": "Generacion de deal flow.",
        "mna_relevance": 2,
        "mna_label": "Interes limitado",
        "example_use_case": "Nuevos actores en el mercado de asesoramiento.",
        "category": "manager",
    },
    "esi": {
        "code": "ESI",
        "name": "Empresa de Servicios de Inversion",
        "short_description": "Intermediario financiero regulado.",
        "long_description": "Incluye agencias y sociedades de valores que ejecutan operaciones financieras y prestan servicios de inversion.",
        "buyer_relevance": "Participacion en procesos corporativos y financiacion.",
        "mna_relevance": 3,
        "mna_label": "Interes medio",
        "example_use_case": "Intermediarios en operaciones de M&A y financiacion corporativa.",
        "category": "manager",
    },
    "ficc": {
        "code": "FICC",
        "name": "Fondo de Inversion Colectiva de Tipo Cerrado",
        "short_description": "Vehiculo de inversion especializado en activos no liquidos.",
        "long_description": "Fondo cerrado que invierte en activos alternativos como inmobiliario, infraestructuras o private equity.",
        "buyer_relevance": "Posible inversor en activos alternativos.",
        "mna_relevance": 3,
        "mna_label": "Interes medio",
        "example_use_case": "Inversor potencial en activos no cotizados.",
        "category": "vehicle",
    },
    "sicc": {
        "code": "SICC",
        "name": "Sociedad de Inversion Colectiva de Tipo Cerrado",
        "short_description": "Sociedad que canaliza inversion hacia activos privados.",
        "long_description": "Estructura societaria cerrada para inversion en activos alternativos y private equity.",
        "buyer_relevance": "Posible vehiculo de inversion.",
        "mna_relevance": 3,
        "mna_label": "Interes medio",
        "example_use_case": "Vehiculo inversor en operaciones de M&A.",
        "category": "vehicle",
    },
    "scr_pyme": {
        "code": "SCR Pyme",
        "name": "Sociedad de Capital Riesgo Pyme",
        "short_description": "SCR especializada en empresas de menor tamano.",
        "long_description": "Sociedad de capital riesgo con enfoque en pequenas y medianas empresas, tipicamente con tickets de inversion menores.",
        "buyer_relevance": "Comprador financiero para pymes.",
        "mna_relevance": 4,
        "mna_label": "Relevante",
        "example_use_case": "Comprador ideal para empresas pequenas en procesos de venta.",
        "category": "vehicle",
    },
    "fcr_pyme": {
        "code": "FCR Pyme",
        "name": "Fondo de Capital Riesgo Pyme",
        "short_description": "Fondo especializado en pymes.",
        "long_description": "Fondo de capital riesgo con mandato de inversion enfocado en pequenas y medianas empresas.",
        "buyer_relevance": "Comprador financiero para pymes.",
        "mna_relevance": 4,
        "mna_label": "Relevante",
        "example_use_case": "Comprador financiero potencial para empresas con facturacion media-baja.",
        "category": "vehicle",
    },
    "fese": {
        "code": "FESE",
        "name": "Fondo de Emprendimiento Social Europeo",
        "short_description": "Fondo especializado en inversion de impacto.",
        "long_description": "Vehiculo europeo que invierte en empresas con impacto social positivo, combinando rentabilidad financiera con impacto social.",
        "buyer_relevance": "Inversor de impacto.",
        "mna_relevance": 2,
        "mna_label": "Interes limitado",
        "example_use_case": "Inversor para empresas con componente social o medioambiental.",
        "category": "vehicle",
    },
    "filpe": {
        "code": "FILPE",
        "name": "Fondo de Inversion a Largo Plazo Europeo",
        "short_description": "Vehiculo disenado para financiar proyectos empresariales a largo plazo.",
        "long_description": "Fondo europeo de largo plazo que invierte en activos reales, infraestructuras y empresas con horizonte temporal extendido.",
        "buyer_relevance": "Inversor a largo plazo.",
        "mna_relevance": 2,
        "mna_label": "Interes limitado",
        "example_use_case": "Inversor para proyectos a largo plazo o infraestructuras.",
        "category": "vehicle",
    },
}


def get_entity_info(entity_type: str) -> dict:
    """Get catalog info for an entity type."""
    return CNMV_ENTITY_CATALOG.get(entity_type, {})


def get_full_catalog() -> list:
    """Get full catalog as list with all info."""
    return [{"entity_type": k, **v} for k, v in CNMV_ENTITY_CATALOG.items()]
