"""TARIC → CNAE Mapping — Official correspondence for trade data.

TARIC (Integrated Tariff of the European Communities) uses 2-digit chapters (01-99)
for product classification. CNAE-2009 uses industry classification.
Relationship is N:M: one TARIC can map to multiple CNAEs and vice versa.

Source: INE correspondence tables + domain knowledge.
"""

# ══════════════════════════════════════════
# TARIC chapters (2-digit) with labels
# ══════════════════════════════════════════

TARIC_CHAPTERS = {
    "01": "Animales vivos", "02": "Carne y despojos comestibles",
    "03": "Pescados, crustaceos, moluscos", "04": "Leche, productos lacteos; huevos",
    "05": "Otros productos de origen animal", "06": "Plantas vivas; productos floricultura",
    "07": "Legumbres, hortalizas", "08": "Frutas/frutos",
    "09": "Cafe, te, yerba mate y especias", "10": "Cereales",
    "11": "Productos de la molineria; malta", "12": "Semillas oleaginosas; plantas industriales",
    "13": "Jugos y extractos vegetales", "14": "Materias trenzables",
    "15": "Grasas, aceite animal o vegetal", "16": "Conservas de carne o pescado",
    "17": "Azucares; articulos confiteria", "18": "Cacao y sus preparaciones",
    "19": "Productos de cereales, de pasteleria", "20": "Conservas verdura o fruta; zumos",
    "21": "Preparaciones alimenticias diversas", "22": "Bebidas todo tipo (exc. zumos)",
    "23": "Residuos industria alimentaria", "24": "Tabaco y sus sucedaneos",
    "25": "Sal, yeso, piedras s/ trabajar", "26": "Minerales, escorias y cenizas",
    "27": "Combustibles, aceites minerales", "28": "Productos quimicos inorganicos",
    "29": "Productos quimicos organicos", "30": "Productos farmaceuticos",
    "31": "Abonos", "32": "Tanino; materias colorantes; pinturas",
    "33": "Aceites esenciales; perfumeria", "34": "Jabones; lubricantes; ceras",
    "35": "Materias albuminoideas; colas", "36": "Polvoras y explosivos",
    "37": "Productos fotograficos o cinematograficos", "38": "Otros productos quimicos",
    "39": "Materias plasticas; sus manufacturas", "40": "Caucho y sus manufacturas",
    "41": "Pieles (exc. peleteria); cueros", "42": "Manufacturas de cuero, marroquineria",
    "43": "Peleteria y sus confecciones", "44": "Madera y sus manufacturas",
    "45": "Corcho y sus manufacturas", "46": "Manufacturas de cesteria",
    "47": "Pasta de madera; papel reciclado", "48": "Papel, carton; sus manufacturas",
    "49": "Libros, publicaciones; artes graficas", "50": "Seda",
    "51": "Lana y pelo fino", "52": "Algodon",
    "53": "Otras fibras textiles vegetales", "54": "Filamentos sinteticos o artificiales",
    "55": "Fibras sinteticas, artificiales discontinuas", "56": "Fieltro, tela s/ tejer; cordel",
    "57": "Alfombras; revestimientos textiles", "58": "Terciopelo; c/ bucles; tapiceria",
    "59": "Tejidos tecnicos, recubiertos", "60": "Tejidos de punto",
    "61": "Prendas de vestir, de punto", "62": "Prendas de vestir, no de punto",
    "63": "Articulos textil-hogar; prenderia", "64": "Calzado; sus partes",
    "65": "Articulos de sombrereria", "66": "Paraguas; sombrillas; bastones",
    "67": "Plumas y plumon preparados", "68": "Manufacturas de piedra, yeso",
    "69": "Productos ceramicos", "70": "Vidrio y sus manufacturas",
    "71": "Piedra, metales preciosos; joyeria", "72": "Fundicion, hierro y acero",
    "73": "Manufacturas de fundicion, hierro/acero", "74": "Cobre y sus manufacturas",
    "75": "Niquel y sus manufacturas", "76": "Aluminio y sus manufacturas",
    "78": "Plomo y sus manufacturas", "79": "Cinc y sus manufacturas",
    "80": "Estano y sus manufacturas", "81": "Otros metales comunes; cermets",
    "82": "Herramientas y cuchilleria metalica", "83": "Manufacturas diversas de metales",
    "84": "Maquinas y aparatos mecanicos", "85": "Aparatos y material electricos",
    "86": "Vehiculos, material ferroviario", "87": "Vehiculos automoviles; tractores",
    "88": "Aeronaves; vehiculos espaciales", "89": "Barcos y embarcaciones",
    "90": "Aparatos opticos, medida, medicos", "91": "Relojeria",
    "92": "Instrumentos musicales", "93": "Armas y municiones; accesorios",
    "94": "Muebles, sillas, lamparas", "95": "Juguetes, juegos, articulos deportivos",
    "96": "Manufacturas diversas", "97": "Objetos de arte; antiguedades",
    "98": "Conjuntos industriales", "99": "Conjuntos de otros productos",
    "00": "Comercio confidencial",
}

# ══════════════════════════════════════════
# Default TARIC → CNAE mapping (N:M)
# Based on INE correspondence tables
# ══════════════════════════════════════════

DEFAULT_TARIC_TO_CNAE = {
    # Agriculture & Food (TARIC 01-24 → CNAE A + C food divisions)
    "01": [{"cnae": "01", "confidence": 0.9}],
    "02": [{"cnae": "10", "confidence": 0.9}],
    "03": [{"cnae": "03", "confidence": 0.7}, {"cnae": "10", "confidence": 0.3}],
    "04": [{"cnae": "01", "confidence": 0.4}, {"cnae": "10", "confidence": 0.6}],
    "05": [{"cnae": "01", "confidence": 0.5}, {"cnae": "10", "confidence": 0.5}],
    "06": [{"cnae": "01", "confidence": 0.9}],
    "07": [{"cnae": "01", "confidence": 0.9}],
    "08": [{"cnae": "01", "confidence": 0.9}],
    "09": [{"cnae": "10", "confidence": 0.9}],
    "10": [{"cnae": "01", "confidence": 0.5}, {"cnae": "10", "confidence": 0.5}],
    "11": [{"cnae": "10", "confidence": 0.9}],
    "12": [{"cnae": "01", "confidence": 0.6}, {"cnae": "10", "confidence": 0.4}],
    "13": [{"cnae": "10", "confidence": 0.9}],
    "14": [{"cnae": "01", "confidence": 0.5}, {"cnae": "16", "confidence": 0.5}],
    "15": [{"cnae": "10", "confidence": 0.9}],
    "16": [{"cnae": "10", "confidence": 0.9}],
    "17": [{"cnae": "10", "confidence": 0.9}],
    "18": [{"cnae": "10", "confidence": 0.9}],
    "19": [{"cnae": "10", "confidence": 0.9}],
    "20": [{"cnae": "10", "confidence": 0.9}],
    "21": [{"cnae": "10", "confidence": 0.9}],
    "22": [{"cnae": "11", "confidence": 0.9}],
    "23": [{"cnae": "10", "confidence": 0.9}],
    "24": [{"cnae": "12", "confidence": 0.9}],
    # Minerals & Chemicals (TARIC 25-38 → CNAE B + C chemicals)
    "25": [{"cnae": "08", "confidence": 0.8}, {"cnae": "23", "confidence": 0.2}],
    "26": [{"cnae": "07", "confidence": 0.9}],
    "27": [{"cnae": "19", "confidence": 0.7}, {"cnae": "06", "confidence": 0.3}],
    "28": [{"cnae": "20", "confidence": 0.9}],
    "29": [{"cnae": "20", "confidence": 0.9}],
    "30": [{"cnae": "21", "confidence": 0.9}],
    "31": [{"cnae": "20", "confidence": 0.9}],
    "32": [{"cnae": "20", "confidence": 0.9}],
    "33": [{"cnae": "20", "confidence": 0.9}],
    "34": [{"cnae": "20", "confidence": 0.9}],
    "35": [{"cnae": "20", "confidence": 0.9}],
    "36": [{"cnae": "20", "confidence": 0.9}],
    "37": [{"cnae": "26", "confidence": 0.9}],
    "38": [{"cnae": "20", "confidence": 0.9}],
    # Plastics, Rubber (TARIC 39-40 → CNAE 22)
    "39": [{"cnae": "22", "confidence": 0.9}],
    "40": [{"cnae": "22", "confidence": 0.9}],
    # Leather, Textiles, Footwear (TARIC 41-67 → CNAE 13-15)
    "41": [{"cnae": "15", "confidence": 0.9}],
    "42": [{"cnae": "15", "confidence": 0.9}],
    "43": [{"cnae": "14", "confidence": 0.9}],
    "44": [{"cnae": "16", "confidence": 0.9}],
    "45": [{"cnae": "16", "confidence": 0.9}],
    "46": [{"cnae": "16", "confidence": 0.9}],
    "47": [{"cnae": "17", "confidence": 0.9}],
    "48": [{"cnae": "17", "confidence": 0.9}],
    "49": [{"cnae": "18", "confidence": 0.9}],
    "50": [{"cnae": "13", "confidence": 0.9}],
    "51": [{"cnae": "13", "confidence": 0.9}],
    "52": [{"cnae": "13", "confidence": 0.9}],
    "53": [{"cnae": "13", "confidence": 0.9}],
    "54": [{"cnae": "13", "confidence": 0.9}],
    "55": [{"cnae": "13", "confidence": 0.9}],
    "56": [{"cnae": "13", "confidence": 0.9}],
    "57": [{"cnae": "13", "confidence": 0.9}],
    "58": [{"cnae": "13", "confidence": 0.9}],
    "59": [{"cnae": "13", "confidence": 0.9}],
    "60": [{"cnae": "13", "confidence": 0.9}],
    "61": [{"cnae": "14", "confidence": 0.9}],
    "62": [{"cnae": "14", "confidence": 0.9}],
    "63": [{"cnae": "13", "confidence": 0.5}, {"cnae": "14", "confidence": 0.5}],
    "64": [{"cnae": "15", "confidence": 0.9}],
    "65": [{"cnae": "14", "confidence": 0.9}],
    "66": [{"cnae": "32", "confidence": 0.9}],
    "67": [{"cnae": "14", "confidence": 0.9}],
    # Stone, Ceramics, Glass (TARIC 68-70 → CNAE 23)
    "68": [{"cnae": "23", "confidence": 0.9}],
    "69": [{"cnae": "23", "confidence": 0.9}],
    "70": [{"cnae": "23", "confidence": 0.9}],
    # Metals (TARIC 71-83 → CNAE 24-25)
    "71": [{"cnae": "32", "confidence": 0.5}, {"cnae": "24", "confidence": 0.5}],
    "72": [{"cnae": "24", "confidence": 0.9}],
    "73": [{"cnae": "25", "confidence": 0.9}],
    "74": [{"cnae": "24", "confidence": 0.9}],
    "75": [{"cnae": "24", "confidence": 0.9}],
    "76": [{"cnae": "24", "confidence": 0.9}],
    "78": [{"cnae": "24", "confidence": 0.9}],
    "79": [{"cnae": "24", "confidence": 0.9}],
    "80": [{"cnae": "24", "confidence": 0.9}],
    "81": [{"cnae": "24", "confidence": 0.9}],
    "82": [{"cnae": "25", "confidence": 0.9}],
    "83": [{"cnae": "25", "confidence": 0.9}],
    # Machinery & Electronics (TARIC 84-85 → CNAE 26-28)
    "84": [{"cnae": "28", "confidence": 0.7}, {"cnae": "27", "confidence": 0.3}],
    "85": [{"cnae": "26", "confidence": 0.5}, {"cnae": "27", "confidence": 0.5}],
    # Transport (TARIC 86-89 → CNAE 29-30)
    "86": [{"cnae": "30", "confidence": 0.9}],
    "87": [{"cnae": "29", "confidence": 0.9}],
    "88": [{"cnae": "30", "confidence": 0.9}],
    "89": [{"cnae": "30", "confidence": 0.9}],
    # Instruments, Misc (TARIC 90-97)
    "90": [{"cnae": "26", "confidence": 0.5}, {"cnae": "32", "confidence": 0.5}],
    "91": [{"cnae": "26", "confidence": 0.9}],
    "92": [{"cnae": "32", "confidence": 0.9}],
    "93": [{"cnae": "25", "confidence": 0.9}],
    "94": [{"cnae": "31", "confidence": 0.9}],
    "95": [{"cnae": "32", "confidence": 0.9}],
    "96": [{"cnae": "32", "confidence": 0.9}],
    "97": [{"cnae": "32", "confidence": 0.9}],
    "98": [{"cnae": "28", "confidence": 0.5}, {"cnae": "33", "confidence": 0.5}],
    "99": [{"cnae": "32", "confidence": 0.5}],
}
