"""Watchlist + Alerts (Q7 — Transaction Intelligence: seguimiento de empresas concretas).

Verified before writing this (do not re-derive without re-checking the code): there was
no watchlist concept anywhere in this codebase — `"add_to_watchlist"` only existed as a
canonical action LABEL suggested by the Signal Engine's taxonomy
(`services/engines/signal/actions.py`), with no persistence or logic behind it. There is
also no outbound email/push infrastructure in this repo (only an inbound IMAP reader for
editorial ingestion, `editorial/email_agent.py`) — so this module deliberately ships
IN-APP alerts only. Extending to email/push requires new infra (SMTP/SES/SendGrid) that
does not exist today; that is an explicit, documented follow-up, not done here.

Design (reuses real, already-persisted data — no new signal computation):
- `watchlist`: one document per (user_id, master_id) a user is following.
- `watchlist_alerts`: one document per (user_id, signal_id) the user hasn't seen yet —
  generated by cross-referencing `db.signals` (Q1's persisted, real signals, with
  lifecycle fields from Q4: `status`, `first_detected_at`) against each user's watched
  companies. Deduplicated on (user_id, signal_id) so a still-active signal never
  re-alerts on every scheduler sweep.

`sync_alerts_for_user()` is called both synchronously right after a user adds a watch
(so they see what's already known about a company immediately) and periodically by
`watchlist_scheduler.py` (so alerts appear for signals detected AFTER the watch began).
"""

import uuid
from typing import Dict, List, Optional

from database import db
from models import now_iso

_INDEXED = False


async def ensure_indexes() -> None:
    global _INDEXED
    if _INDEXED:
        return
    await db.watchlist.create_index([("user_id", 1), ("master_id", 1)], unique=True)
    await db.watchlist.create_index("user_id")
    await db.watchlist_alerts.create_index([("user_id", 1), ("signal_id", 1)], unique=True)
    await db.watchlist_alerts.create_index([("user_id", 1), ("read", 1)])
    _INDEXED = True


# ── Watchlist CRUD ──

async def add_watch(user_id: str, master_id: str, notes: Optional[str] = None) -> Dict:
    """Idempotent: watching an already-watched company just returns the existing doc
    (never creates a duplicate — enforced by the unique index above)."""
    await ensure_indexes()
    existing = await db.watchlist.find_one({"user_id": user_id, "master_id": master_id}, {"_id": 0})
    if existing:
        return existing
    doc = {"watch_id": "wl_" + uuid.uuid4().hex[:12], "user_id": user_id, "master_id": master_id,
           "notes": notes, "created_at": now_iso()}
    await db.watchlist.insert_one(dict(doc))
    return doc


async def remove_watch(user_id: str, master_id: str) -> bool:
    res = await db.watchlist.delete_one({"user_id": user_id, "master_id": master_id})
    return res.deleted_count > 0


async def list_watches(user_id: str) -> List[Dict]:
    return await db.watchlist.find({"user_id": user_id}, {"_id": 0}).sort("created_at", -1).to_list(500)


async def _watched_master_ids(user_id: str) -> List[str]:
    rows = await db.watchlist.find({"user_id": user_id}, {"_id": 0, "master_id": 1}).to_list(500)
    return [r["master_id"] for r in rows]


# ── Alerts ──

async def sync_alerts_for_user(user_id: str) -> Dict:
    """Generates any missing in-app alerts for this user's watched companies, from
    REAL active signals already persisted by the Signal Engine (Q1) — never computes
    a new signal, only surfaces what already exists. Idempotent via the unique index
    on (user_id, signal_id): re-running this for the same still-active signal is a
    no-op, it does not spam a new alert every sweep."""
    await ensure_indexes()
    master_ids = await _watched_master_ids(user_id)
    if not master_ids:
        return {"user_id": user_id, "alerts_created": 0}

    created = 0
    async for sig in db.signals.find(
        {"master_id": {"$in": master_ids}, "status": "active"},
        {"_id": 0, "signal_id": 1, "master_id": 1, "signal_type": 1, "category": 1,
         "detected_at": 1, "first_detected_at": 1, "explanation": 1},
    ):
        alert = {
            "alert_id": "wa_" + uuid.uuid4().hex[:12], "user_id": user_id,
            "master_id": sig["master_id"], "signal_id": sig["signal_id"],
            "signal_type": sig.get("signal_type"), "category": sig.get("category"),
            "signal_detected_at": sig.get("first_detected_at") or sig.get("detected_at"),
            "explanation": sig.get("explanation"),
            "created_at": now_iso(), "read": False, "read_at": None,
        }
        try:
            await db.watchlist_alerts.insert_one(dict(alert))
            created += 1
        except Exception:
            continue  # duplicate key -> already alerted for this (user, signal), skip silently
    return {"user_id": user_id, "alerts_created": created}


async def sync_alerts_all() -> Dict:
    """Scheduler-facing sweep: runs `sync_alerts_for_user` for every distinct user with
    at least one watch. Cheap — bounded by number of active watchers, not by the size
    of `master_companies`."""
    user_ids = await db.watchlist.distinct("user_id")
    total_created = 0
    for uid in user_ids:
        result = await sync_alerts_for_user(uid)
        total_created += result["alerts_created"]
    return {"users_checked": len(user_ids), "alerts_created": total_created}


async def list_alerts(user_id: str, unread_only: bool = False, limit: int = 50) -> List[Dict]:
    q: Dict = {"user_id": user_id}
    if unread_only:
        q["read"] = False
    return await db.watchlist_alerts.find(q, {"_id": 0}).sort("created_at", -1).to_list(limit)


async def mark_alert_read(user_id: str, alert_id: str) -> bool:
    res = await db.watchlist_alerts.update_one(
        {"user_id": user_id, "alert_id": alert_id},
        {"$set": {"read": True, "read_at": now_iso()}},
    )
    return res.modified_count > 0


async def unread_count(user_id: str) -> int:
    return await db.watchlist_alerts.count_documents({"user_id": user_id, "read": False})
